server:
  port: 8887
  servlet:
    context-path: /org-note-function
spring:
  application:
    name: org-note-function
  profiles:
    active: dev
#-----------------------------------DAO层-mybatis-2/2[开始]-----------------------------------------------
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  path: /usr/local/domi/app
  level:
    root: info
#-----------------------------------注册到注册中心[开始]--------------------------------------------------
eureka:
  instance:
    prefer-ip-address: true  #将自己的ip注册到eureka上
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
