clusterServersConfig:
  idleConnectionTimeout: 10001
  pingTimeout: 1002
  connectTimeout: 10002
  timeout: 3003
  retryAttempts: 3
  retryInterval: 1503
  reconnectionTimeout: 3004
  failedAttempts: 3
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveSubscriptionConnectionMinimumIdleSize: 1
  slaveSubscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 32
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 32
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  nodeAddresses:
    - "redis://192.168.15.128:7001"
    - "redis://192.168.15.128:7002"
    - "redis://192.168.15.128:7003"
    - "redis://192.168.15.128:7004"
    - "redis://192.168.15.128:7005"
    - "redis://192.168.15.128:7006"
  scanInterval: 1000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: NIO